version: "3.9"
x-common: &common
  restart: unless-stopped
  tty: true
services:
  mongo:
    <<: *common
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_DATABASE: TP
    ports:
      - "27017:27017"
    networks:
      tp_network:
        aliases:
          - mongo
        ipv4_address: 172.255.254.103
    volumes:
      - $PWD/.data/mongodb:/data/db:delegated
networks:
  tp_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.255.254.0/24
  backend:
    driver: bridge
