application:
  security:
    jwt:
      expiration: 43200000
      refresh-token:
        expiration: 43200000
      secret-key: ${SECRET_KEY}
server:
  port: 8091
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
monitor:
  time-range: 2


