application:
  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 86400000
      secret-key: ${SECRET_KEY}
server:
  port: 8099
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
monitor:
  time-range: ${MONITOR_TIME_RANGE}
