application:
  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 86400000
      secret-key: ${SECRET_KEY}
server:
  port: 8091
spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?serverSelectionTimeoutMS=5000&connectTimeoutMS=5000
      auto-index-creation: true
monitor:
  time-range: ${MONITOR_TIME_RANGE}